"use client";
import { AppPanel } from "@/components/ui/AppPanel";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, Bell, CalendarCheck, CalendarDays, Check, Clock3, CreditCard, Grid2X2, Leaf, RefreshCw, Settings2, TriangleAlert, Users, Zap } from "lucide-react";
import { useTranslation } from "@/components/settings/LocalizedText";
import { useUserPreferences } from "@/components/settings/UserPreferencesApplier";
import { getBranchCapabilityDecision } from "@/lib/branchCapabilities";
import type { DashboardOverview } from "@/lib/dashboardContracts";
import type { BranchAccess } from "@/types";
import { SourceState } from "./ReferenceDashboard";
import { ActivityLink } from "./ActivityLink";
import { activityDetailLabels } from "@/lib/dashboardLabels";

type Props = { data: DashboardOverview; base: string; retry: () => void };
export function ActionCenter({ data, base, refresh }: { data: DashboardOverview; base: string; refresh: () => void }) {
    const t = useTranslation(); const { formatNumber } = useUserPreferences();
    const money = data.money.data; const follow = data.followUps.data; const attendance = data.attendance.data; const seats = data.seating.data; const terms = data.terms.data;
    const items = [
        { key: "overdue", icon: TriangleAlert, tone: "red", label: "Overdue collections", value: money ? formatNumber(money.overdueAmount, { style: "currency", currency: "INR", maximumFractionDigits: 0 }) : "—", note: money ? t.owned("{count} students need follow-up", { count: formatNumber(money.overdueStudents) }) : "", action: "Review now", href: "/renewals?filter=OVERDUE", source: data.money, active: !!money?.overdueStudents },
        { key: "followups", icon: Users, tone: "amber", label: "Follow-ups due today", value: follow ? formatNumber(follow.dueToday) : "—", note: t.owned("Scheduled contacts due"), action: "View list", href: "/follow-ups?filter=DUE", source: data.followUps, active: !!follow?.dueToday },
        { key: "attendance", icon: CalendarDays, tone: "blue", label: "Attendance gaps today", value: attendance?.configured ? formatNumber(attendance.gaps) : "—", note: t.owned(attendance?.configured ? "Expected but not checked in" : "Set attendance expectations"), action: attendance?.configured ? "View students" : "Set up", href: attendance?.configured ? "/dashboard-settings?section=expectations&filter=gaps" : "/dashboard-settings?section=expectations", source: data.attendance, active: !!attendance?.gaps },
        { key: "utilization", icon: BarChart3, tone: "purple", label: seats?.lowUtilization ? "Low utilization" : "Seat utilization", value: seats?.utilizationPercent == null ? "—" : `${formatNumber(seats.utilizationPercent, { maximumFractionDigits: 0 })}%`, note: seats ? t("{used} of {total} shift slots", { used: formatNumber(seats.occupied), total: formatNumber(seats.capacity) }) : "", action: "Review seats", href: "/dashboard-settings?section=utilization", source: data.seating, active: !!seats?.lowUtilization },
        { key: "renewals", icon: RefreshCw, tone: "green", label: "Renewals this week", value: terms?.configured ? formatNumber(terms.renewalsThisWeek) : "—", note: t.owned(terms?.configured ? "Membership terms ending soon" : "Set membership term dates"), action: terms?.configured ? "View renewals" : "Set up", href: "/dashboard-settings?section=terms", source: data.terms, active: !!terms?.renewalsThisWeek },
    ];
    return <AppPanel density="compact" padding="none" className="rd-action-center" aria-labelledby="rd-action-title"><div className="rd-panel-heading"><div><Bell size={21} fill="currentColor" /><h2 id="rd-action-title">{t("Action Center")}</h2><span className="rd-count">{formatNumber(items.filter(item => item.active).length)}</span><p>{t.owned("Things that need your attention right now")}</p></div><Link href={`${base}/tasks`}>{t.owned("View all tasks")}<ArrowRight size={14} /></Link></div><div className="rd-priorities">{items.map(item => <article key={item.key} data-tone={item.tone}><span className="rd-priority-icon"><item.icon size={26} /></span><div><strong>{item.value}</strong><h3>{t.owned(item.label)}</h3><p>{item.note}</p>{item.source.status === "success" ? <Link className="rd-priority-action" href={`${base}${item.href}`}>{t.owned(item.action)}<ArrowRight size={13} /></Link> : <SourceState source={item.source} retry={refresh} />}</div></article>)}</div></AppPanel>;
}

export function DashboardActivity({ data, base }: Pick<Props, "data" | "base">) {
    const t = useTranslation(); const { formatDateTime, formatNumber } = useUserPreferences();
    const icons = { COLLECTION: CreditCard, STUDENT: Users, ATTENDANCE: Grid2X2, FOLLOW_UP: Clock3, TASK: Check, ALLOCATION: Users, CONFIGURATION: Settings2 };
    const labels = { COLLECTION: "Payment received", STUDENT: "New student added", ATTENDANCE: "Attendance recorded", FOLLOW_UP: "Follow-up updated", TASK: "Task updated", ALLOCATION: "Allocation began", CONFIGURATION: "Settings updated" };
    if (data.activityStatus === "error") return <AppPanel density="compact" padding="none" className="rd-panel rd-activity"><h2>{t("Recent activity")}</h2><p className="rd-source">{t("Recent activity could not be verified because one or more data sources failed.")}</p></AppPanel>;
    return <AppPanel density="compact" padding="none" className="rd-panel rd-activity"><div className="rd-panel-heading"><div><Clock3 size={18} /><h2>{t("Recent activity")}</h2></div><Link href={`${base}/tasks?view=activity`}>{t("View all")}<ArrowRight size={12} /></Link></div><div className="rd-activity-list">{data.activity.slice(0, 5).map(item => { const Icon = icons[item.kind]; const minutes = Math.max(0, Math.floor((Date.parse(data.updatedAt) - Date.parse(item.occurredAt)) / 60_000)); return <ActivityLink key={item.id} href={item.href} className="rd-activity-row"><span className={`rd-activity-icon rd-event-${item.kind.toLowerCase()}`}><Icon size={16} /></span><span><strong>{t.owned(labels[item.kind])}</strong><span>{item.amount != null ? `${formatNumber(item.amount, { style: "currency", currency: "INR", maximumFractionDigits: 0 })} · ` : ""}{item.studentName ?? (item.detail && activityDetailLabels[item.detail] ? t.owned(activityDetailLabels[item.detail]) : item.detail ?? "")}</span></span><time dateTime={item.occurredAt} title={formatDateTime(item.occurredAt)}>{minutes < 60 ? t.owned("{count}m ago", { count: formatNumber(minutes) }) : minutes < 1440 ? t.owned("{count}h ago", { count: formatNumber(Math.floor(minutes / 60)) }) : t.owned("{count}d ago", { count: formatNumber(Math.floor(minutes / 1440)) })}</time></ActivityLink>; })}{!data.activity.length && <p className="rd-empty">{t("No recent activity")}</p>}</div></AppPanel>;
}

export function DashboardQuickActions({ access, base }: { access: BranchAccess; base: string }) {
    const t = useTranslation();
    const actions = [
        { icon: Users, label: "Add student", href: "/students?action=add", allowed: getBranchCapabilityDecision(access, "studentsManage").allowed },
        { icon: CreditCard, label: "Record payment", href: "/payments?action=collect", allowed: getBranchCapabilityDecision(access, "paymentsRecord").allowed },
        { icon: CalendarCheck, label: "Mark attendance", href: "/attendance", allowed: access.permissions.students },
        { icon: Grid2X2, label: "Assign seat", href: "/allocations", allowed: getBranchCapabilityDecision(access, "allocationsManage").allowed },
        { icon: BarChart3, label: "Generate report", href: "/reports", allowed: access.permissions.view_payments || access.permissions.students },
        { icon: Clock3, label: "Manage shifts", href: "/shifts", allowed: getBranchCapabilityDecision(access, "shiftsView").allowed },
    ].filter(action => action.allowed);
    return <section className="rd-quick"><div className="rd-panel-heading"><div><Zap size={21} fill="currentColor" /><h2>{t("Quick actions")}</h2></div></div><nav aria-label={t("Quick actions")}>{actions.map(action => action.href === "/attendance" ? <a key={action.href} href={`${base}${action.href}`}><action.icon size={17} />{t.owned(action.label)}</a> : <Link key={action.href} href={`${base}${action.href}`}><action.icon size={17} />{t.owned(action.label)}</Link>)}</nav><div className="rd-quick-quote"><Image src="/images/dashboard/botanical-sprig.png" alt="" width={55} height={60} /><span>{t.owned("Small steps.")}<br />{t.owned("Fuller futures.")}</span><Leaf size={16} /></div></section>;
}

export function DashboardWorklists(props: Props) { return <div className="rd-worklists"><Renewals {...props} /><FollowUps {...props} /></div>; }
function Renewals({ data, base, retry }: Props) {
    const t = useTranslation(); const { formatDate, formatNumber } = useUserPreferences(); const terms = data.terms.data;
    return <AppPanel density="compact" padding="none" className="rd-panel rd-renewals"><div className="rd-panel-heading"><div><CalendarDays size={18} /><div><h2>{t.owned("Upcoming renewals")}</h2><p>{t.owned("Students with membership terms ending soon.")}</p></div></div>{data.terms.status !== "restricted" && <Link href={`${base}/dashboard-settings?section=terms`}>{t("View all")}<ArrowRight size={12} /></Link>}</div>{terms ? terms.configured ? <div className="rd-table-scroll"><table><thead><tr>{["Student name", "Term", "End date", "Days left", "Status", "Action"].map(label => <th key={label}>{t.owned(label)}</th>)}</tr></thead><tbody>{terms.items.slice(0, 3).map(term => <tr key={term.id}><td>{term.studentName}</td><td>{term.label}</td><td>{formatDate(`${term.endDate.slice(0,10)}T12:00:00Z`, { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" })}</td><td>{t.owned("{count} days", { count: formatNumber(term.daysLeft) })}</td><td><span className={`rd-badge ${term.daysLeft <= 3 ? "rd-urgent" : "rd-soon"}`}>{t.owned(term.daysLeft <= 3 ? "Urgent" : "Soon")}</span></td><td><Link className="rd-table-action" href={`${base}/dashboard-settings?section=terms&studentId=${encodeURIComponent(term.studentId)}`}>{t.owned("Review")}</Link></td></tr>)}</tbody></table>{!terms.items.length && <p className="rd-empty">{t.owned("No membership terms ending this week.")}</p>}</div> : <div className="rd-empty"><p>{t.owned("Membership terms are not configured.")}</p><Link href={`${base}/dashboard-settings?section=terms`}>{t.owned("Set membership term dates")} <ArrowRight size={13} /></Link><small>{t.owned("Terms do not change fee dates or student status.")}</small></div> : <SourceState source={data.terms} retry={retry} />}</AppPanel>;
}
function FollowUps({ data, base, retry }: Props) {
    const t = useTranslation(); const { formatDate } = useUserPreferences();
    return <AppPanel density="compact" padding="none" className="rd-panel rd-followups"><div className="rd-panel-heading"><div><Users size={19} /><div><h2>{t.owned("Follow-up queue")}</h2><p>{t.owned("Students who need attention.")}</p></div></div>{data.followUps.status !== "restricted" && <Link href={`${base}/follow-ups`}>{t("View all")}<ArrowRight size={12} /></Link>}</div>{data.followUps.data ? <div className="rd-table-scroll"><table><thead><tr>{["Student name", "Issue", "Due date", "Priority", "Action"].map(label => <th key={label}>{t.owned(label)}</th>)}</tr></thead><tbody>{data.followUps.data.items.slice(0, 4).map(row => { const due = !!row.nextFollowUpAt && row.nextFollowUpAt.slice(0,10) <= data.today; return <tr key={row.id}><td>{row.studentName}</td><td>{t.owned(row.outcome === "PROMISED_PAYMENT" ? "Payment promised" : "Scheduled follow-up")}</td><td>{row.nextFollowUpAt ? row.nextFollowUpAt.slice(0,10) === data.today ? t("Today") : formatDate(row.nextFollowUpAt, { day: "numeric", month: "short" }) : "—"}</td><td><span className={`rd-badge ${due ? "rd-urgent" : "rd-soon"}`}>{t.owned(due ? "High" : "Scheduled")}</span></td><td><Link className="rd-table-action" href={`${base}/follow-ups?search=${encodeURIComponent(row.studentName)}`}>{t.owned("Review")}</Link></td></tr>; })}</tbody></table>{!data.followUps.data.items.length && <p className="rd-empty">{t.owned("No pending follow-ups.")}</p>}</div> : <SourceState source={data.followUps} retry={retry} />}</AppPanel>;
}
