-- Drain import and WhatsApp writers. No historical ownership is guessed.
BEGIN;
LOCK TABLE "ImportPlan", "ImportQuestion", "ImportRow", "ImportRowEvaluation", "ImportRun", "ImportRunItem", "ImportSession", "Payment", "WhatsAppMessage", "WhatsAppMessagePayment" IN SHARE ROW EXCLUSIVE MODE;
DO $$ DECLARE n bigint; BEGIN
SELECT (SELECT COUNT(*) FROM "ImportRun" c JOIN (SELECT id,"branchId" FROM "ImportRun") own ON own.id=c."id" WHERE c."importSessionId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM (SELECT id,"branchId" FROM "ImportSession") p WHERE p.id=c."importSessionId" AND p."branchId"=own."branchId")) INTO n; IF n > 0 THEN RAISE EXCEPTION 'TI_ImportRun_session_branchId: % inconsistent references require reviewed repair', n; END IF;
SELECT (SELECT COUNT(*) FROM "ImportRun" c JOIN (SELECT id,"branchId" FROM "ImportRun") own ON own.id=c."id" WHERE c."importPlanId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM (SELECT p.id,s."branchId" FROM "ImportPlan" p JOIN "ImportSession" s ON s.id=p."importSessionId") p WHERE p.id=c."importPlanId" AND p."branchId"=own."branchId")) INTO n; IF n > 0 THEN RAISE EXCEPTION 'TI_ImportRun_plan_branchId: % inconsistent references require reviewed repair', n; END IF;
SELECT (SELECT COUNT(*) FROM "ImportRunItem" c JOIN (SELECT i.id,r."branchId" FROM "ImportRunItem" i JOIN "ImportRun" r ON r.id=i."importRunId") own ON own.id=c."id" WHERE c."importRowId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM (SELECT r.id,s."branchId" FROM "ImportRow" r JOIN "ImportSession" s ON s.id=r."importSessionId") p WHERE p.id=c."importRowId" AND p."branchId"=own."branchId")) INTO n; IF n > 0 THEN RAISE EXCEPTION 'TI_ImportRunItem_row_branchId: % inconsistent references require reviewed repair', n; END IF;
SELECT (SELECT COUNT(*) FROM "ImportRunItem" c JOIN (SELECT i.id,r."branchId" FROM "ImportRunItem" i JOIN "ImportRun" r ON r.id=i."importRunId") own ON own.id=c."id" WHERE c."evaluationId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM (SELECT e.id,s."branchId" FROM "ImportRowEvaluation" e JOIN "ImportRow" r ON r.id=e."importRowId" JOIN "ImportSession" s ON s.id=r."importSessionId") p WHERE p.id=c."evaluationId" AND p."branchId"=own."branchId")) INTO n; IF n > 0 THEN RAISE EXCEPTION 'TI_ImportRunItem_evaluation_branchId: % inconsistent references require reviewed repair', n; END IF;
SELECT (SELECT COUNT(*) FROM "WhatsAppMessagePayment" c JOIN (SELECT m.id,m."branchId" FROM "WhatsAppMessage" m) own ON own.id=c."messageId" WHERE c."paymentId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM (SELECT id,"branchId" FROM "Payment") p WHERE p.id=c."paymentId" AND p."branchId"=own."branchId")) INTO n; IF n > 0 THEN RAISE EXCEPTION 'TI_WhatsAppMessagePayment_payment_branchId: % inconsistent references require reviewed repair', n; END IF;
SELECT (SELECT COUNT(*) FROM "ImportQuestion" q WHERE q."rowId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "ImportRow" r WHERE r.id=q."rowId" AND r."importSessionId"=q."importSessionId")) INTO n; IF n > 0 THEN RAISE EXCEPTION 'ImportQuestion_row_session: % inconsistent references require reviewed repair', n; END IF;
END $$;
ALTER TABLE "ImportRow" ADD COLUMN "branchId" TEXT;
UPDATE "ImportRow" c SET "branchId"=p."branchId" FROM (SELECT r.id,s."branchId" FROM "ImportRow" r JOIN "ImportSession" s ON s.id=r."importSessionId") p WHERE p.id=c."id";
ALTER TABLE "ImportRow" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "ImportRowEvaluation" ADD COLUMN "branchId" TEXT;
UPDATE "ImportRowEvaluation" c SET "branchId"=p."branchId" FROM (SELECT e.id,s."branchId" FROM "ImportRowEvaluation" e JOIN "ImportRow" r ON r.id=e."importRowId" JOIN "ImportSession" s ON s.id=r."importSessionId") p WHERE p.id=c."id";
ALTER TABLE "ImportRowEvaluation" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "ImportPlan" ADD COLUMN "branchId" TEXT;
UPDATE "ImportPlan" c SET "branchId"=p."branchId" FROM (SELECT p.id,s."branchId" FROM "ImportPlan" p JOIN "ImportSession" s ON s.id=p."importSessionId") p WHERE p.id=c."id";
ALTER TABLE "ImportPlan" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "ImportRunItem" ADD COLUMN "branchId" TEXT;
UPDATE "ImportRunItem" c SET "branchId"=p."branchId" FROM (SELECT i.id,r."branchId" FROM "ImportRunItem" i JOIN "ImportRun" r ON r.id=i."importRunId") p WHERE p.id=c."id";
ALTER TABLE "ImportRunItem" ALTER COLUMN "branchId" SET NOT NULL;
ALTER TABLE "WhatsAppMessagePayment" ADD COLUMN "branchId" TEXT;
UPDATE "WhatsAppMessagePayment" c SET "branchId"=p."branchId" FROM (SELECT m.id,m."branchId" FROM "WhatsAppMessage" m) p WHERE p.id=c."messageId";
ALTER TABLE "WhatsAppMessagePayment" ALTER COLUMN "branchId" SET NOT NULL;
CREATE UNIQUE INDEX "ImportSession_id_branchId_key" ON "ImportSession"(id,"branchId");
CREATE UNIQUE INDEX "ImportRow_id_branchId_key" ON "ImportRow"(id,"branchId");
CREATE UNIQUE INDEX "ImportRowEvaluation_id_branchId_key" ON "ImportRowEvaluation"(id,"branchId");
CREATE UNIQUE INDEX "ImportPlan_id_branchId_key" ON "ImportPlan"(id,"branchId");
CREATE UNIQUE INDEX "ImportRun_id_branchId_key" ON "ImportRun"(id,"branchId");
ALTER TABLE "ImportRow" DROP CONSTRAINT "ImportRow_importSessionId_fkey", ADD CONSTRAINT "TI_ImportRow_session_branchId" FOREIGN KEY ("importSessionId","branchId") REFERENCES "ImportSession"(id,"branchId") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ImportRowEvaluation" DROP CONSTRAINT "ImportRowEvaluation_importRowId_fkey", ADD CONSTRAINT "TI_ImportRowEvaluation_row_branchId" FOREIGN KEY ("importRowId","branchId") REFERENCES "ImportRow"(id,"branchId") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ImportPlan" DROP CONSTRAINT "ImportPlan_importSessionId_fkey", ADD CONSTRAINT "TI_ImportPlan_session_branchId" FOREIGN KEY ("importSessionId","branchId") REFERENCES "ImportSession"(id,"branchId") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ImportRun" DROP CONSTRAINT "ImportRun_importSessionId_fkey", ADD CONSTRAINT "TI_ImportRun_session_branchId" FOREIGN KEY ("importSessionId","branchId") REFERENCES "ImportSession"(id,"branchId") ON DELETE SET NULL ("importSessionId") ON UPDATE CASCADE;
ALTER TABLE "ImportRun" DROP CONSTRAINT "ImportRun_importPlanId_fkey", ADD CONSTRAINT "TI_ImportRun_plan_branchId" FOREIGN KEY ("importPlanId","branchId") REFERENCES "ImportPlan"(id,"branchId") ON DELETE SET NULL ("importPlanId") ON UPDATE CASCADE;
ALTER TABLE "ImportRunItem" DROP CONSTRAINT "ImportRunItem_importRunId_fkey", ADD CONSTRAINT "TI_ImportRunItem_run_branchId" FOREIGN KEY ("importRunId","branchId") REFERENCES "ImportRun"(id,"branchId") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ImportRunItem" DROP CONSTRAINT "ImportRunItem_importRowId_fkey", ADD CONSTRAINT "TI_ImportRunItem_row_branchId" FOREIGN KEY ("importRowId","branchId") REFERENCES "ImportRow"(id,"branchId") ON DELETE SET NULL ("importRowId") ON UPDATE CASCADE;
ALTER TABLE "ImportRunItem" DROP CONSTRAINT "ImportRunItem_evaluationId_fkey", ADD CONSTRAINT "TI_ImportRunItem_evaluation_branchId" FOREIGN KEY ("evaluationId","branchId") REFERENCES "ImportRowEvaluation"(id,"branchId") ON DELETE SET NULL ("evaluationId") ON UPDATE CASCADE;
ALTER TABLE "WhatsAppMessagePayment" DROP CONSTRAINT "WhatsAppMessagePayment_messageId_fkey", ADD CONSTRAINT "TI_WhatsAppMessagePayment_message_branchId" FOREIGN KEY ("messageId","branchId") REFERENCES "WhatsAppMessage"(id,"branchId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "WhatsAppMessagePayment" DROP CONSTRAINT "WhatsAppMessagePayment_paymentId_fkey", ADD CONSTRAINT "TI_WhatsAppMessagePayment_payment_branchId" FOREIGN KEY ("paymentId","branchId") REFERENCES "Payment"(id,"branchId") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE UNIQUE INDEX "ImportRow_id_importSessionId_key" ON "ImportRow"(id,"importSessionId");
ALTER TABLE "ImportQuestion" ADD CONSTRAINT "ImportQuestion_rowId_importSessionId_fkey" FOREIGN KEY ("rowId","importSessionId") REFERENCES "ImportRow"(id,"importSessionId") ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;
